### ISSUE TITLE
J'arrive pas à lancer le serveur Django !

### ISSUE THREAD

**Issue by abotsi** [fschmitt7/NeoDetection#8]
Bonsoir ! ^^'
Du coup pour savoir, vous utilisez quelles version de python ? et Django ? Est-ce que vous êtes bien sous Ubuntu ?

**Comment by fschmitt7** [comment]
2.7 python, et django 1.8 il me semble, mais peut importe la version normalement

**Comment by abotsi** [comment]
J'ai la même en python,  mais je suis à django 1.6, et je crois au contraire que ca change pas mal ! Tu l'as installé comment ?

**Comment by fschmitt7** [comment]
non, django j'suis en 1.7.7

**Comment by fschmitt7** [comment]
bah j'avais suivi ce qu'il y a dans le lien que j'ai mis dans le readme

**Comment by abotsi** [comment]
J'ai bien vu le lien du readme, mais il est vaste x) 
Juste pour l'installation de django, t'as tapé $sudo apt-get install python-django ?

**Comment by fschmitt7** [comment]
Installing an official release with pip¶

This is the recommended way to install Django.

Install pip. The easiest is to use the standalone pip installer. If your distribution already has pip installed, you might need to update it if it’s outdated. (If it’s outdated, you’ll know because installation won’t work.)

(optional) Take a look at virtualenv and virtualenvwrapper. These tools provide isolated Python environments, which are more practical than installing packages systemwide. They also allow installing packages without administrator privileges. It’s up to you to decide if you want to learn and use them.

If you’re using Linux, Mac OS X or some other flavor of Unix, enter the command sudo pip install Django at the shell prompt. If you’re using Windows, start a command shell with administrator privileges and run the command pip install Django. This will install Django in your Python installation’s site-packages directory.

If you’re using a virtualenv, you don’t need sudo or administrator privileges, and this will install Django in the virtualenv’s site-packages directory.

**Comment by abotsi** [comment]
C'est bon, j'ai réinstallé avec pip et il m'a mis la version 1.8. Ça fonctionne !
